name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build backend Docker image
        run: |
          docker build -t mbruckert/wardrobe-wizard-backend:latest -f api/Dockerfile .

      - name: Build frontend Docker image
        run: |
          docker build -t mbruckert/wardrobe-wizard-frontend:latest -f frontend/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push backend Docker image
        run: docker push mbruckert/wardrobe-wizard-backend:latest

      - name: Push frontend Docker image
        run: docker push mbruckert/wardrobe-wizard-frontend:latest

      - name: Deploy to DigitalOcean
        env:
          HOST: "134.209.125.222"
          USER: root
        run: |
          # Write the SSH private key to a temporary file
          echo "${{ secrets.SSH_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

          # SSH into the server and pull & run the Docker containers
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no $USER@$HOST << EOF
            docker pull mbruckert/wardrobe-wizard-backend:latest
            docker pull mbruckert/wardrobe-wizard-frontend:latest
            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true
            docker run -d --name backend -p 3000:3000 mbruckert/wardrobe-wizard-backend:latest
            docker run -d --name frontend -p 80:80 mbruckert/wardrobe-wizard-frontend:latest
          EOF
