name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build backend Docker image
        run: |
          docker build -t mbruckert/wardrobe-wizard-backend:latest -f api/Dockerfile .

      - name: Build frontend Docker image
        run: |
          docker build -t mbruckert/wardrobe-wizard-frontend:latest -f frontend/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push backend Docker image
        run: docker push mbruckert/wardrobe-wizard-backend:latest

      - name: Push frontend Docker image
        run: docker push mbruckert/wardrobe-wizard-frontend:latest

      - name: Deploy to DigitalOcean
        env:
          HOST: "134.209.125.222"
          USER: root
          SSH_KEY_BASE64: ${{ secrets.SSH_KEY_BASE64 }}
        run: |
          # Decode and write the SSH private key
          echo "$SSH_KEY_BASE64" | base64 --decode > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

          # Test SSH connection with verbose output
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no -v $USER@$HOST exit

          # SSH into the server and execute commands
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Pull the latest Docker images
            docker pull mbruckert/wardrobe-wizard-backend:latest
            docker pull mbruckert/wardrobe-wizard-frontend:latest

            # Stop and remove existing containers if they exist
            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true

            # Run the backend container
            docker run -d --name backend -p 3000:3000 mbruckert/wardrobe-wizard-backend:latest

            # Run the frontend container
            docker run -d --name frontend -p 80:80 mbruckert/wardrobe-wizard-frontend:latest
          EOF
