name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build backend Docker image
        run: |
          docker build -t mbruckert/backend:latest -f backend/Dockerfile .

      - name: Build frontend Docker image
        run: |
          docker build -t mbruckert/frontend:latest -f frontend/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push backend Docker image
        run: docker push mbruckert/backend:latest

      - name: Push frontend Docker image
        run: docker push mbruckert/frontend:latest

      - name: Deploy to DigitalOcean
        env:
          SSH_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          HOST: your-droplet-ip
          USER: root
        run: |
          ssh -i $SSH_KEY -o StrictHostKeyChecking=no $USER@$HOST << EOF
            docker pull mbruckert/backend:latest
            docker pull mbruckert/frontend:latest
            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true
            docker run -d --name backend -p 3000:3000 mbruckert/backend:latest
            docker run -d --name frontend -p 80:80 mbruckert/frontend:latest
          EOF
